### ISSUE TITLE
no consensus fasta file produced

### ISSUE THREAD

**Issue by Wei-Shao** [ChrisHIV/shiver#15]
I have been trying to use shiver for a set of illumina data. SPAdes produced a single good and long HIV contig. shiver_align_contigs.sh  produced a _shiverBiuld_raw_wRefs.fasta , but not a _shiverBiuld_cut_wRefs.fasta. shiver_map_reads.sh  did not produce a consensus fasta file. What could be the problem? Thanks.

**Comment by ChrisHIV** [comment]
Hi there. When you need code developers to debug a problem (for shiver but also in general), you need to provide enough detail for them to figure out the problem. To start with, what were the exact commands you ran and what was all of the output printed to the command line as a result of those commands?

**Comment by Wei-Shao** [comment]
Here are the command and the output messages:
%shiver_align_contigs.sh shiver_init_dir config.sh contigs.fasta index_N7-NFL_shiverBiuld
Warning: [blastn] Examining 5 or more matches is recommended
Info: the --addfragments mafft option did not produce a better alignment than --add did when aligning temp_HIVcontigs_uncut1.fasta to the existing references. Using the --add result. (Alignment length: 12040 for --add and 12040 for add fragments).
Info: the alignment of just the existing references has length 12025; after adding the contigs, the alignment index_N7-NFL_shiverBiuld_raw_wRefs.fasta has length 12040, i.e. the total length of insertions in the contigs not present in any reference (as inferred by this alignment) is 15.
No contig correction needed for index_N7-NFL_shiverBiuld.blast.

A different dataset produced good result with the same command. It produced _shiverBuild_cut_wRefs.fasta file.

**Comment by ChrisHIV** [comment]
As explained in the manual, shiver_align_contigs only produces a _cut_wRefs.fasta file if contig correction is needed; the last line of the output above states that contig correction was not needed.
