### ISSUE TITLE
Suggestion to rename FindSeqsInFasta.py within shiver and/or phyloscanner 'tools' folders

### ISSUE THREAD

**Issue by vera-rykalina** [ChrisHIV/shiver#17]
Hi Chris! Hope you are doing great. This is just a kind suggestion to rename FindSeqsInFasta.py within shiver and/or phyloscanner 'tools' folders. The scripts have the same name, but they are different what can produce a lot of confusion if one wants to pipeline both tools (shiver & phyloscanner), fusing the 'tools' folders of both into a common one within a bin. Without noticing it in the first place, I rewrote the shiver's FindSeqsInFasta.py by the phyloscanner's one and got an error which took me quite some time to fix as I just could not get what was going on.  I had to go through the relevant code chunks before I found out the root cause of my issue. Thanks, Vera.

**Comment by ChrisHIV** [comment]
Hi Vera. I've not heard of anyone manually merging code from two repositories into a shared directory before; sounds like a bad idea in general as it might cause this or other problems. Best to leave each repository in a separate directory as they're intended, then direct any dependent code to the appropriate repo in each case.

**Comment by vera-rykalina** [comment]
Hi Chris! Thanks a lot for your reply. You are quite right that generally it is not a good approach and I usually don't do it. However, as shiver and phyloscanner go hand in hand, to merge their corresponding folders seemed to me as natural as having both phyloscanner parts in one dedicated folder. Anyway, an idea to go this way was supported by a desire to reduce unwanted parameters in a Nextflow workflow and to call the appropriate scripts naturally, assuming they reside within a bin/. Unfortunately, changing a directory level prevents direct usage of the scripts.
I, personally, only renamed the FindSeqsInFasta.py related to phyloscanner to FindSeqsInFastaPhyloscanner.py and took it into account in the phyloscanner_make_trees.py.
And you are also right that my merge can reveal some other issues later on in the case of using some individual scripts within tools. For instance, the clean_bams.bash needs a firm phyloscanner location (phyDir="~/phyloscanner"), but it is outside of my workflow and, hence, should not bring problems.
Anyway, the aim of my post here was to draw attention of other users to a potential issue they may encounter, if they like me would like to merge the respective tools folders for some reason. Nothing more than that!

By the way, is there any update on listing the phyloscannerR package on CRAN? It could indeed facilitate an automated installation of the tool. Thanks, Vera.

**Comment by ChrisHIV** [comment]
Roger that, have renamed it just within phyloscanner (I was slightly more wary of renaming it within shiver).
No update on phyloscannerR -> CRAN: the lead, Matthew Hall, says it just requires a lot of drudgery which there isn't time for at the moment...

**Comment by vera-rykalina** [comment]
Hi Chris! Thank you for considering my suggestion and extra thanks for the information regarding phyloscannerR/CRAN query. I

**Comment by mdhall272** [comment]
For what it's worth it's possible to install R packages directly from GitHub if that helps with automation? https://cloud.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html

**Comment by vera-rykalina** [comment]
Hi Matthew. That might be an option. I should check, if I manage it using conda.
