### ISSUE TITLE
Shiver for HTLV-1?

### ISSUE THREAD

**Issue by ammaraziz** [ChrisHIV/shiver#18]
Hi Chris,

Do you think Shiver could also be used for HTLV-1?

**Comment by ammaraziz** [comment]
Apologies this was accidental.

**Comment by ChrisHIV** [comment]
I know nothing about HTLV, except that its genome is single segment (i.e. not in multiple segments like flu), so I expect shiver would work. All I think you need to change is setting the `GiveHXB2coords` variable in `config.sh` to `false`, as that's HIV specific. Good luck!
