### ISSUE TITLE
Problem aligning

### ISSUE THREAD

**Issue by jsan4christ** [ChrisHIV/shiver#19]
I run the command:
cd SID && ../../shiver/shiver_align_contigs.sh \
 ../ShiverInitDir \
../../shiver/config.sh \
SID/contigs.fasta \
 SID && cd ..

I get the error below but it does not give any indication as to how to resolve.

Problem aligning temp_HIVcontigs_uncut1.fasta using mafft.
Problem aligning the raw contigs to refs. Quitting.

Please advise.

**Comment by ChrisHIV** [comment]
Apologies, I missed this in the Christmas rush! Is that the complete error message? If no, can you include the complete message? If yes, can you attach minimal data needed for me to reproduce the error?
