### ISSUE TITLE
Inquiry about Using Shiver Software Output for HIV Drug Resistance Prediction

### ISSUE THREAD

**Issue by cvn001** [ChrisHIV/shiver#22]
Hello,

I'm interested in using the output results from the Shiver software for HIV drug resistance prediction. Could you please advise if it's possible to utilize Shiver's output for this purpose? Additionally, how can I convert the output results into a format that is recognizable by the HIVdb, such as a Codon Frequency (CodFreq) format file?

Thank you.

Xiangchen

**Comment by ChrisHIV** [comment]
Hi there!

> I'm interested in using the output results from the Shiver software for HIV drug resistance prediction. Could you please advise if it's possible to utilize Shiver's output for this purpose?  

There are different ways of doing HIV drug resistance prediction. shiver outputs viral sequence data, so if your drug resistance prediction is based on viral sequence data, then yes!

> the HIVdb 

I don't know what this is

> a Codon Frequency (CodFreq) format file 

I don't know what this is

The two most relevant files for you in shiver output are probably the .bam file, containing mapped reads, or the consensus file obtained by calling the most common base at every position. You could either provide mapped reads individually, or the consensus, to an algorithm predicting drug resistance from sequences, such as the Stanford algorithm.
