### ISSUE TITLE
error if too many (contaminant) contigs

### ISSUE THREAD

**Issue by CarlijnB** [ChrisHIV/shiver#6]
Hi Chris,

I'd like to try out shiver with some metagenomic read sets and assemblies, and reference alignments for various viruses (each done in turn).

Trying one sample with a large number of contigs (>100000, most of which "contaminant"), I get the following error: 
./shiver-1.3.3/shiver_map_reads.sh: line 347: ./shiver-1.3.3/tools/FindSeqsInFasta.py: Argument list too long
.. because the shell can't deal with so many arguments. It results in the temporary RefAndContaminantContigs blast database being built with only the reference, but no contaminant contigs.

I know metagenomic assemblies are not what your tool was designed for, but I wonder whether you would be willing to address this issue anyway (if there is an easy way around it)?

Many thanks,

Carlijn

**Comment by ChrisHIV** [comment]
Hi Carlijn, thanks for the interest. That sounds like something I can fix, though I'm afraid probably not before Jan 29th.

**Comment by CarlijnB** [comment]
Thanks Chris! 
A quick google appeared to suggest it was the length of the argument, rather than the number of separate arguments, that would be the issue.

**Comment by ChrisHIV** [comment]
Hi Carlijn, sorry for the delay. I think the latest pushed change should solve the issue - the contig names are now passed between steps via a file. Let me know...

**Comment by CarlijnB** [comment]
Hi Chris,
Thanks for looking at this. I've just downloaded shiver-master and have been playing around with it.

Sorry, I don't actually know yet whether your original fix works - I'm now getting different issues.
The same test data is now giving me bother about trimmomatic ("Error running 'trimmomatic -version"), despite having config.sh set to TrimReadsForAdaptersAndQual=false.
My reads should already have been cleaned, and I do not have trimmomatic installed. Any quick fix to tell shiver this, other than just installing trimmomatic regardless? 

Another set of data has issues shortly after BLASTing contigs against ref alignments. It generates the .blast file, but then I get:
/home/s1144826/progs/shiver-master/shiver_funcs.sh: line 617: HIVContigsListOrig: unbound variable
/home/s1144826/progs/shiver-master/shiver_funcs.sh: line 618: HIVContigsListOrig: unbound variable
It subsequently just quits/moves on to the next sample without further message.
Any advice?

Thanks again!
Carlijn

**Comment by ChrisHIV** [comment]
Hi Carlijn, sorry for the delay. I'm guessing what's happening here is that you've set TrimReadsForAdaptersAndQual=false in your new version of config.sh, but you're providing an old version of config.sh as the argument when you run a shiver command. Can you confirm/refute? I can't see from the code how you would get the former error unless TrimReadsForAdaptersAndQual=true.
