### ISSUE TITLE
Error running with Mafft

### ISSUE THREAD

**Issue by 398jw** [ChrisHIV/shiver#8]
Hello,

I am very interested in shiver for my hepatitis B virus work. 
I have encounter an error with mafft in the "shiver.align_contigs.sh" step. Please see commands below. I have used the example datasets from the program.  
I installed mafft with conda and mafft is running fine from anywhere in terminal. Do I still have to specific the path for mafft, even when installed with conda. Please let us know. 
Thanks very much,
Josef 

sh shiver_init.sh MyInitDir config_original.sh HIV1_REF_2010_env_DNA.fasta adapters_Illumina.fasta primers_GallEtAl2012.fasta 

Building a new DB, current time: 06/19/2018 09:20:55
New DB name:   /Users/wagnerj/09_shiver/shiver-master/MyInitDir/ExistingRefsBlastDatabase
New DB title:  /Users/wagnerj/09_shiver/shiver-master/MyInitDir/ExistingRefsUngapped.fasta
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 170 sequences in 0.0232549 seconds.

Informations-MacBook:shiver-master wagnerj$ sh shiver_align_contigs.sh MyInitDir config_original.sh MysteryHIV_contigs.fasta Mystery
Error running 'mafft'. Are you sure that mafft is installed, and that you chose the right value for the config file variable 'mafft'?
Problem with config_original.sh. Quitting.
Informations-MacBook:shiver-master wagnerj$

**Comment by 398jw** [comment]
I just found out myself that somehow conda installed mafft program could not be find by "silver_align_contigs.sh" no idea why. So I installed mafft manually and add it to the path manually. Now the "silver_align_contigs.sh" script is running. Josef

**Comment by ChrisHIV** [comment]
Glad to hear it.
(For anyone else looking at this thread: the value of the `mafft` variable in the config file must be set to whatever command is needed to run mafft; if the mafft executable's directory is not in your $PATH then that directory should be included in the `mafft` config file variable.)
