### ISSUE TITLE
TranslateSeqForGlobalAln.py Error

### ISSUE THREAD

**Issue by MichaelVirology** [ChrisHIV/shiver#9]
Hi Chris,

Thanks for developing the great tool for virus genome reconstruction. When I used TranslateSeqForGlobalAln.py to generate a consensus for global alignment, I got an error as follows:

```
Traceback (most recent call last):
  File "/home/user/shiver/tools/TranslateSeqForGlobalAln.py", line 47, in <module>
    if seq == None:
  File "/usr/local/lib/python2.7/dist-packages/Bio/SeqRecord.py", line 748, in __eq__
    raise NotImplementedError(_NO_SEQRECORD_COMPARISON)
NotImplementedError: SeqRecord comparison is deliberately not implemented. Explicitly compare the attributes of interest.
```

I found something similar on this website: https://www.rosettacommons.org/node/10197
So I changed `if seq == None:` to `if seq is None:`, then TranslateSeqForGlobalAln.py seems to work well. I was wondering if this is the right way to correct this error?

Best wishes,
Michael

**Comment by ChrisHIV** [comment]
Hi Michael, sorry for the delay. The change I've just pushed should fix this - can you git pull and confirm?

**Comment by MichaelVirology** [comment]
Hi Chris,
Sorry for the delay. I just tried to use TranslateSeqForGlobalAln.py again and it worked well this time. Thank you very much.
Best, Michael
